//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaSofttek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public long Id { get; set; }
        public string Titulo { get; set; }
        public int Ano { get; set; }
        public int Genero { get; set; }
        public int NumeroPaginas { get; set; }
        public long IdAutor { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Autor Autor { get; set; }
    }
}
